# 张量


张量, 描述具有任意数量轴的维数组的通用方法。 例如，向量是一阶张量，矩阵是二阶张量。

无论使用哪个深度学习框架，它的*张量类*（在MXNet中为`ndarray`，
在PyTorch和TensorFlow中为`Tensor`）都与Numpy的`ndarray`类似。
但深度学习框架又比Numpy的`ndarray`多一些重要功能：
首先，GPU很好地支持加速计算，而NumPy仅支持CPU计算；
其次，张量类支持自动微分。
这些功能使得张量类更适合深度学习。
如果没有特殊说明，本书中所说的张量均指的是张量类的实例。


In [1]:
# 虽然它被称为PyTorch，但是代码中使用`torch`而不是`pytorch`。
import torch

## 创建张量

张量中的每个值都称为张量的 *元素*（element）。例如，张量 `x` 中有 12 个元素。除非额外指定，新的张量将存储在内存中，并采用基于CPU的计算。


In [4]:
# `arange` 创建一个行向量 `x`
X = torch.arange(12)
X

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
# 全0
# a = torch.zeros((2, 3, 4)),元组格式也行
a = torch.zeros(2, 3, 4)
b = torch.zeros_like(X)
# 全1
c = torch.ones(2, 3, 4)
d = torch.ones_like(X)
# 单位矩阵
f = torch.eye(3, 3)

a, b, c, d, f

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 tensor([[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]))

In [33]:
# 其中的每个元素都从均匀分布[0, 1]中随机采样。
torch.rand(3, 4)

tensor([[0.4049, 0.1729, 0.4959, 0.3172],
        [0.5403, 0.5851, 0.7314, 0.9184],
        [0.8569, 0.3803, 0.6517, 0.0221]])

In [4]:
# 其中的每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样。
torch.randn(3, 4)

tensor([[-0.2176,  1.0872, -0.4403,  1.5302],
        [-0.6766,  0.9808, -2.1340, -0.5039],
        [ 0.6986, -1.3820, -0.5058, -0.9808]])

In [35]:
# 限定元素大小 [min, max)
a = torch.randint(10, 12, (3, 4))
# 默认最小0
b = torch.randint(2, (3, 4))
a, b

(tensor([[11, 10, 10, 10],
         [10, 10, 10, 11],
         [10, 11, 10, 11]]),
 tensor([[0, 1, 1, 0],
         [1, 0, 0, 0],
         [0, 1, 0, 0]]))

In [6]:
# Python列表
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 浮点数

`torch.arange()`, `torch.eye()`默认是整数,其他默认是浮点数. 可通过`dtype=torch.float32`来指定

In [8]:
torch.arange(12, dtype=torch.float32)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

或者使用`.float()`

In [16]:
torch.arange(12).float()

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
a = torch.arange(12).dtype
b = torch.arange(12).float().dtype
a, b

(torch.int64, torch.float32)

## 张量的维度

In [18]:
# 标量
X = torch.tensor(8)
# 没有 X = torch.arange(...)
# X = torch.ones(size=())
# X = torch.randn(size=())
print(X, X.shape, sep='\n')

tensor(8)
torch.Size([])


In [5]:
# 张量（沿每个轴的长度）的形状
X = torch.arange(12)
print(X, X.shape, len(X), sep='\n')

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12


In [21]:
# 要想改变一个张量的形状
X = torch.arange(12).reshape(3, 4)
print(X, X.shape, X.shape[0], X.shape[-1], len(X), sep='\n')

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
3
4
3


在这里，最外层的列表对应于轴0，内层的列表对应于轴1。


我们不需要通过手动指定每个维度来改变形状。
也就是说，如果我们的目标形状是（高度,宽度），
那么在知道宽度后，高度会被自动计算得出，不必我们自己做除法。
在上面的例子中，为了获得一个3行的矩阵，我们手动指定了它有3行和4列。
幸运的是，我们可以通过`-1`来调用此自动计算出维度的功能。

In [8]:
# 用`x.reshape(-1,4)`或`x.reshape(3,-1)`来取代`x.reshape(3,4)`。
X.reshape(-1, 4), X.reshape(3, -1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [9]:
# 还可以化为列向量 `x.reshape(-1)`
X.reshape(-1)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
# 1维n列
X.reshape(-1, 12)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [12]:
# n维1列
X.reshape(-1,1)

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])

## 运算



### 标量和张量

In [88]:
X = torch.arange(9).reshape((3, 3))

f = 2 + X
g = 2 * X
h = 2 ** X

f, g, h

(tensor([[ 2,  3,  4],
         [ 5,  6,  7],
         [ 8,  9, 10]]),
 tensor([[ 0,  2,  4],
         [ 6,  8, 10],
         [12, 14, 16]]),
 tensor([[  1,   2,   4],
         [  8,  16,  32],
         [ 64, 128, 256]]))

### 加减乘除幂

In [5]:
X = torch.arange(9).reshape((3, 3))
Y = torch.arange(9).reshape((3, 3))

a = X + Y
b = X - Y
c = X / Y
d = X * Y   # 按元素相乘，不是内积. 若是矩阵, 即Hadamard product
e = torch.mul(X, Y)
f = X ** Y  # 求幂运算

X, Y, a, b, c, d, e, f

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[ 0,  2,  4],
         [ 6,  8, 10],
         [12, 14, 16]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[nan, 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 0,  1,  4],
         [ 9, 16, 25],
         [36, 49, 64]]),
 tensor([[ 0,  1,  4],
         [ 9, 16, 25],
         [36, 49, 64]]),
 tensor([[       1,        1,        4],
         [      27,      256,     3125],
         [   46656,   823543, 16777216]]))

In [89]:
torch.exp(X)

tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00],
        [2.0086e+01, 5.4598e+01, 1.4841e+02],
        [4.0343e+02, 1.0966e+03, 2.9810e+03]])

### 向量的点积

In [83]:
# torch.dot 限定 1D 向量
a = torch.dot(torch.tensor([1, 2, 3]), torch.tensor([2, 0, 0]))

# 相当于
b = (torch.tensor([1, 2, 3]) * torch.tensor([2, 0, 0])).sum()

a, b

(tensor(2), tensor(2))

In [4]:
# 通用的torch.matmul
torch.matmul(torch.tensor([1, 2, 3]), torch.tensor([2, 0, 0]))

tensor(2)

In [14]:
torch.tensor([1, 2, 3]) @ torch.tensor([2, 0, 0])

tensor(2)

### 矩阵-向量积

In [15]:
A = torch.arange(9).reshape(3,3)
x = torch.tensor([1,2,3])

# 限定 matrix-vector (vector-matrix 不能颠倒)
print(torch.mv(A, x))

# 通用的torch.matmul (可以vector-matrix)
print(torch.matmul(A, x))

print(A@x)

tensor([ 8, 26, 44])
tensor([ 8, 26, 44])
tensor([ 8, 26, 44])


### 矩阵-矩阵乘法

In [16]:
X = torch.arange(9).reshape((3, 3))
Y = torch.ones_like(X)

# 限定 matrix-matrix multiplication
print(torch.mm(X, Y))

# 通用的torch.matmul (可以vector-matrix)
print(torch.matmul(X, Y))

print(X@Y)

tensor([[ 3,  3,  3],
        [12, 12, 12],
        [21, 21, 21]])
tensor([[ 3,  3,  3],
        [12, 12, 12],
        [21, 21, 21]])
tensor([[ 3,  3,  3],
        [12, 12, 12],
        [21, 21, 21]])


### 矩阵的转置

In [9]:
# 转置
A = torch.arange(12).reshape(3, 4)
A.T, A.permute(1, 0)

(tensor([[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]]),
 tensor([[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]]))

### 范数

#### 向量范数

范数是右下角下标, 而不是右上角.

- L1范数, 向量元素的绝对值之和.

  $\|\mathbf{x}\|_1 = \displaystyle \sum_{i=1}^n \left|x_i \right|$.

- L2范数, 向量元素平方和的平方根

  $\|\mathbf{x}\|_2 = \sqrt{\displaystyle \sum_{i=1}^n x_i^2}$. L2在范数中常常省略下标，即$\|\mathbf{x}\|$。
  
- Lp范数

  $\|\mathbf{x}\|_p = \left(\displaystyle \sum_{i=1}^n \left|x_i \right|^p \right)^{1/p}$.
  
  
 注意: $||\mathbf{x}||^2$ ( $||\mathbf{x}||^2_2$ ) 表示L2范数的平方, 即各元素的平方和.
 $||\mathbf{x}||^2= \displaystyle \sum_{i=1}^n x_i^2$

In [93]:
# L1
a = torch.abs(torch.tensor([3.0, -4.0])).sum()

# L2
b = torch.norm(torch.tensor([3.0, -4.0]))

a, b

(tensor(7.), tensor(5.))

#### 矩阵范数

Frobenius范数（Frobenius norm）是矩阵元素平方和的平方根.


$\|\mathbf{X}\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}$.

In [99]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

### 逻辑运算符

In [11]:
# 逻辑运算符
X == Y

tensor([[False,  True, False],
        [False, False, False],
        [False, False, False]])

In [22]:
# 筛选
X, X * (torch.abs(X) >= 5)

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[0, 0, 0],
         [0, 0, 5],
         [6, 7, 8]]))

### 求和

In [69]:
# sum求和

Z = torch.ones(3,4)
print(Z)

# 对张量中的所有元素进行求和，会产生一个单元素张量
print(Z.sum(), Z.shape)

# 沿着轴求和,即输入轴0的维数在输出形状中消失。
print(Z.sum(axis=0), Z.sum(axis=0).shape)
print(Z.sum(axis=1), Z.sum(axis=1).shape)

# 沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和。
print(Z.sum(axis=[0,1]))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor(12.) torch.Size([3, 4])
tensor([3., 3., 3., 3.]) torch.Size([4])
tensor([4., 4., 4.]) torch.Size([3])
tensor(12.)


In [70]:
# 非降维求和

Z.sum(axis=1, keepdims=True)

tensor([[4.],
        [4.],
        [4.]])

In [77]:
# 沿某个轴计算元素的累积总和
# 此函数不会沿任何轴降低输入张量的维度
T = torch.arange(12).reshape(3, 4)
T, T.cumsum(axis=0), T.cumsum(axis=1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  6,  8, 10],
         [12, 15, 18, 21]]),
 tensor([[ 0,  1,  3,  6],
         [ 4,  9, 15, 22],
         [ 8, 17, 27, 38]]))

In [13]:
# 张量中元素的总数，即形状的所有元素乘积
X.numel()

9

In [14]:
# 平均值
# Input dtype must be either a floating point or complex dtype
a = X.float().mean()
# 平均值 = 所有元素求和 / 元素个数
b = X.sum() / X.numel()

a, b

(tensor(4.), tensor(4.))

## 广播机制

即使形状不同，我们仍然可以通过调用*广播机制*（broadcasting mechanism）来执行按元素操作。


In [67]:
# 形状不能是 (3), 得是 (3,1)
X = torch.arange(3).reshape((3, 1))
Y = torch.arange(2).reshape((1, 2))

a = X+Y
X, Y, a

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

- (3,1),(1,2),都扩展为(3,2). 
- 矩阵`X`将复制列，变成`[[0,0], [1,1], [2,2]]`.
- 矩阵`Y`将复制行，变成`[[0,1], [0,1], [0,1]]`
- 然后相加

## 索引和切片

In [15]:
X = torch.arange(12).reshape((3, 4))
X, X[-1], X[1:3], X[1:3, :], X[1,1]

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor(5))

**为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。**


In [16]:
X[0:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

## 内存

### 节省内存

下面将取消引用原来的张量，而是指向新分配的内存处的张量。

这可能是不可取的，原因有两个：首先，我们不想总是不必要地分配内存。
在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。
通常情况下，我们希望原地执行这些更新。其次，如果我们不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数。

In [17]:
X = torch.randn(3,4)
Y = torch.randn(3,4)

# Y = X+Y, 取消Y
before1 = id(Y)
Y = Y + X
after1 = id(Y)

# Z = X+Y, 取消Z
Z = torch.zeros_like(Y)
before2 = id(Z)
Z = X + Y
after2 = id(Z)

before1 == after1, before2 == after2

(False, False)

`X[:] = X + Y`或`X += Y`来减少操作的内存开销。


In [18]:
X = torch.randn(3,4)
Y = torch.randn(3,4)

# Y = X+Y, 取消Y
before1 = id(Y)
Y = Y + X
after1 = id(Y)

# Z = X+Y, 取消Z
Z = torch.zeros_like(Y)
before2 = id(Z)
Z = X + Y
after2 = id(Z)

before1 == after1, before2 == after2

(False, False)

### 克隆

In [11]:
B = X.clone()  # 通过分配新内存，将A的一个副本分配给B
id(B),id(X)

(140167522494000, 140167522493280)

## 转换为其他Python对象


将深度学习框架定义的张量[**转换为NumPy张量（`ndarray`）**]很容易，反之也同样容易。


In [21]:
# Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
A = X.numpy()
B = torch.tensor(A)
A, B, type(A), type(B), id(A), id(B)

(array([[ 3.1535175 , -0.62133527,  0.22701214, -0.9588724 ],
        [ 1.3448218 ,  0.03080277, -0.64052534,  0.66786146],
        [ 1.1358713 , -1.4676546 , -0.14227198, -1.4488608 ]],
       dtype=float32),
 tensor([[ 3.1535, -0.6213,  0.2270, -0.9589],
         [ 1.3448,  0.0308, -0.6405,  0.6679],
         [ 1.1359, -1.4677, -0.1423, -1.4489]]),
 numpy.ndarray,
 torch.Tensor,
 140528396455536,
 140528396402912)

要(**将大小为1的张量转换为Python标量**)，我们可以调用`item`函数或Python的内置函数。


In [7]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 其他
```python
torch.max()

torch.sum()

torch.abs()

# 连接张量
torch.cat()

# 返回指定维度最大值的序号
torch.argmax()

# 升维
torch.unsqueeze()

# 降维
torch.squeeze()

# 交换维度
torch.permute()

# 限定元素大小
torch.clamp()
```

### cat

In [5]:
X = torch.arange(9).reshape((3, 3))
Y = torch.ones_like(X)

# 按外层的列
a = torch.cat((X, Y), dim=0)
# 按内层的列
b = torch.cat((X, Y), dim=1)

X, Y, a, b, a.shape, b.shape

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]),
 tensor([[0, 1, 2, 1, 1, 1],
         [3, 4, 5, 1, 1, 1],
         [6, 7, 8, 1, 1, 1]]),
 torch.Size([6, 3]),
 torch.Size([3, 6]))

### argmax

In [2]:
a = torch.arange(16).reshape(4,4)
a, a.argmax(1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]),
 tensor([3, 3, 3, 3]))

### unsqueeze
unsqueeze()函数起升维的作用,参数表示在哪个地方加一个维度。
在第一个维度(中括号)的每个元素加中括号
0表示在张量最外层加一个中括号变成第一维。

In [4]:
import torch
input=torch.arange(0,6)
print(input)
print(input.shape)

print(input.unsqueeze(0))
print(input.unsqueeze(0).shape)

print(input.unsqueeze(1))
print(input.unsqueeze(1).shape)

tensor([0, 1, 2, 3, 4, 5])
torch.Size([6])
tensor([[0, 1, 2, 3, 4, 5]])
torch.Size([1, 6])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])
torch.Size([6, 1])


### squeeze

- `dim=None`： 删除一个张量中所有维数为1的维度

  例如，一个维度为 $(A \times 1 \times B \times C \times 1 \times D)$的张量调用squeeze方法后维度变为$(A \times B \times C \times D)$

- 当给定dim参数后，squeeze操作只作用于给定维度。

  如果输入input的形状为$(A \times 1 \times B)$, squeeze(input, 0)不改变这个张量, 但是squeeze(input, 1) 将把这个张量的形状变为$(A \times B)$.

In [7]:
x = torch.zeros(2, 1, 2, 1, 2)
y1 = torch.squeeze(x)
y2 = torch.squeeze(x, 0)
y3 = torch.squeeze(x, 1)
x.shape, y1.shape, y2.shape, y3.shape

(torch.Size([2, 1, 2, 1, 2]),
 torch.Size([2, 2, 2]),
 torch.Size([2, 1, 2, 1, 2]),
 torch.Size([2, 2, 1, 2]))

### permute
交换维度

In [8]:
# 转置效果
import torch
input=torch.arange(0,6).reshape(2,3)
print(input)
print(input.permute(1,0))

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [15]:
# 调整图片通道
import torch
# 3通道5x5的图片
input = torch.arange(0, 75).reshape(3, 5, 5)
# 调整(C, H, W) 为 (H, W, C)
output = input.permute(1, 2, 0)
print(input, output)
# 还是同一个元素
print(input[0, 1, 2], output[1, 2, 0])

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74]]]) tensor([[[ 0, 25, 50],
         [ 1, 26, 51],
         [ 2, 27, 52],
         [ 3, 28, 53],
         [ 4, 29, 54]],

        [[ 5, 30, 55],
         [ 6, 31, 56],
         [ 7, 32, 57],
         [ 8, 33, 58],
         [ 9, 34, 59]],

        [[10, 35, 60],
         [11, 36, 61],
         [12, 37, 62],
         [13, 38, 63],
         [14, 39, 64]],

        [[15, 40, 65],
         [16, 41, 66],
         [17, 42, 67],
         [18, 43, 68],
         [19, 44, 69]],

        [[20, 45, 70],
         [21, 46, 71],
         [22, 4

### clamp
限定元素大小 [min, max]

In [51]:
import torch
input = torch.randint(20, (1, 10))
print(input)
output = input.clamp(min=0, max=9)
print(output)

tensor([[15,  4,  8, 11, 12, 18, 11, 12,  8,  0]])
tensor([[9, 4, 8, 9, 9, 9, 9, 9, 8, 0]])
