# 数据操作


首先，我们介绍$n$维数组，也称为*张量*（tensor）。

无论使用哪个深度学习框架，它的*张量类*（在MXNet中为`ndarray`，
在PyTorch和TensorFlow中为`Tensor`）都与Numpy的`ndarray`类似。
但深度学习框架又比Numpy的`ndarray`多一些重要功能：
首先，GPU很好地支持加速计算，而NumPy仅支持CPU计算；
其次，张量类支持自动微分。
这些功能使得张量类更适合深度学习。
如果没有特殊说明，本书中所说的张量均指的是张量类的实例。


In [1]:
# 虽然它被称为PyTorch，但是代码中使用`torch`而不是`pytorch`。
import torch

## 创建张量

[**张量表示由一个数值组成的数组，这个数组可能有多个维度**]。
具有一个轴的张量对应数学上的*向量*（vector）；
具有两个轴的张量对应数学上的*矩阵*（matrix）；
具有两个轴以上的张量没有特殊的数学名称。


首先，这个行向量包含以0开始的前12个整数，它们默认创建为整数。也可指定创建类型为浮点数。张量中的每个值都称为张量的 *元素*（element）。例如，张量 `x` 中有 12 个元素。除非额外指定，新的张量将存储在内存中，并采用基于CPU的计算。


In [2]:
# `arange` 创建一个行向量 `x`
X = torch.arange(12)
X

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# 全0
a = torch.zeros((2, 3, 4))
b = torch.zeros_like(X)
# 全1
c = torch.ones((2, 3, 4))
d = torch.ones_like(X)

a,b,c,d

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [4]:
# 其中的每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样。
torch.randn(3, 4)

tensor([[-0.9308, -0.0894,  0.0592,  1.4720],
        [-0.0344,  0.2529, -0.8291,  1.0957],
        [-2.0980, -0.0545,  0.1464, -0.8242]])

In [5]:
# Python列表
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 张量的属性

In [6]:
# 张量（沿每个轴的长度）的形状
X.shape

torch.Size([12])

In [7]:
# 张量中元素的总数，即形状的所有元素乘积
X.numel()

12

In [8]:
# 要想改变一个张量的形状
torch.arange(12).reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

我们不需要通过手动指定每个维度来改变形状。
也就是说，如果我们的目标形状是（高度,宽度），
那么在知道宽度后，高度会被自动计算得出，不必我们自己做除法。
在上面的例子中，为了获得一个3行的矩阵，我们手动指定了它有3行和4列。
幸运的是，我们可以通过`-1`来调用此自动计算出维度的功能。
即我们可以用`x.reshape(-1,4)`或`x.reshape(3,-1)`来取代`x.reshape(3,4)`。


在这里，最外层的列表对应于轴0，内层的列表对应于轴1。


## 按元素（elementwise）运算



In [9]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

a = x + y
b = x - y,
c = x / y
d = x * y   # 按元素相乘，不是内积
e = x ** y  # 求幂运算

a, b, c, d, e

(tensor([ 3.,  4.,  6., 10.]),
 (tensor([-1.,  0.,  2.,  6.]),),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([ 1.,  4., 16., 64.]))

In [10]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [11]:
# 连接张量
X = torch.arange(12).reshape((3, 4))
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

# 按外层的列
a = torch.cat((X, Y), dim=0)
# 按内层的列
b = torch.cat((X, Y), dim=1)

X, Y, a, b

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 2,  1,  4,  3],
         [ 1,  2,  3,  4],
         [ 4,  3,  2,  1]]),
 tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
         [ 4,  5,  6,  7,  1,  2,  3,  4],
         [ 8,  9, 10, 11,  4,  3,  2,  1]]))

In [12]:
# 逻辑运算符
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [13]:
# 对张量中的所有元素进行求和，会产生一个单元素张量
X.sum()

tensor(66)

## 广播机制

即使形状不同，我们仍然可以通过调用*广播机制*（broadcasting mechanism）来执行按元素操作。


In [14]:
X = torch.arange(3).reshape((3, 1))
Y = torch.arange(2).reshape((1, 2))

a = X+Y
X, Y, a

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

- (3,1),(1,2),都扩展为(3,2). 
- 矩阵`X`将复制列，变成`[[0,0], [1,1], [2,2]]`.
- 矩阵`Y`将复制行，变成`[[0,1], [0,1], [0,1]]`
- 然后相加

## 索引和切片

In [15]:
X = torch.arange(12).reshape((3, 4))
X, X[-1], X[1:3], X[1:3, :], X[1,1]

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor(5))

**为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。**


In [16]:
X[0:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

## 节省内存

下面将取消引用原来的张量，而是指向新分配的内存处的张量。

这可能是不可取的，原因有两个：首先，我们不想总是不必要地分配内存。
在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。
通常情况下，我们希望原地执行这些更新。其次，如果我们不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数。

In [17]:
X = torch.randn(3,4)
Y = torch.randn(3,4)

# Y = X+Y, 取消Y
before1 = id(Y)
Y = Y + X
after1 = id(Y)

# Z = X+Y, 取消Z
Z = torch.zeros_like(Y)
before2 = id(Z)
Z = X + Y
after2 = id(Z)

before1 == after1, before2 == after2

(False, False)

`X[:] = X + Y`或`X += Y`来减少操作的内存开销。


In [18]:
X = torch.randn(3,4)
Y = torch.randn(3,4)

# Y = X+Y, 取消Y
before1 = id(Y)
Y = Y + X
after1 = id(Y)

# Z = X+Y, 取消Z
Z = torch.zeros_like(Y)
before2 = id(Z)
Z = X + Y
after2 = id(Z)

before1 == after1, before2 == after2

(False, False)

## 转换为其他Python对象


将深度学习框架定义的张量[**转换为NumPy张量（`ndarray`）**]很容易，反之也同样容易。


In [21]:
A = X.numpy()
B = torch.tensor(A)
A, B, type(A), type(B), id(A), id(B)

(array([[ 3.1535175 , -0.62133527,  0.22701214, -0.9588724 ],
        [ 1.3448218 ,  0.03080277, -0.64052534,  0.66786146],
        [ 1.1358713 , -1.4676546 , -0.14227198, -1.4488608 ]],
       dtype=float32),
 tensor([[ 3.1535, -0.6213,  0.2270, -0.9589],
         [ 1.3448,  0.0308, -0.6405,  0.6679],
         [ 1.1359, -1.4677, -0.1423, -1.4489]]),
 numpy.ndarray,
 torch.Tensor,
 140528396455536,
 140528396402912)

要(**将大小为1的张量转换为Python标量**)，我们可以调用`item`函数或Python的内置函数。


In [20]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)